_posts/2019-10-31-october-2019.md, images/blog/2019-10-31-october-2019/githubsponsor.png, images/blog/2019-10-31-october-2019/heightmap.png, images/blog/2019-10-31-october-2019/thumb.jpg, images/blog/2019-10-31-october-2019/voxel-global-illumination.png
=> October blog

_posts/2019-12-18-community-meeting-3.md
@xen2 Please check if the blog post contains information that can be made publicly.
=> Community meeting 3 - december 2019

_posts/2019-12-18-community-meeting-3.md, _posts/2019-12-31-december-2019.md, images/blog/2019-12-31-december-2019/fogofwar.png, images/blog/2019-12-31-december-2019/thumb.jpg
Updated previous blogpost about community meeting, added recap blog post for december.
=> December blog2019

index.html
Just made the wording a little more natural.
=> Small wording change in the History section

_posts/2020-05-08-community-meeting-1.md
Community meeting blogpost may 2020
=> Community meeting blogpost may 2020

_posts/2020-05-08-community-meeting-3.md
Fixes the formatting of the bullet points and links.
=> Fixed formatting and links

_posts/2020-05-08-community-meeting-3.md
Run the text through Grammarly
=> Grammarly fixes

_config.yml
Changes the Twitter account name from `stride3d` to `stridedotnet`
Fixes stride3d/stride#704
=> Fixes the Twitter username

index.html
=> Updated to C# 8.0

_posts/2021-02-01-release-stride-4-0.md, images/blog/2021-02-01-release-stride-4-0/launcher-net5.png, index.html
=> Net Core to Net 5

_layouts/sponsors.html, _sass/common.scss, sponsor.html
shows the sponsors centered instead of a fixed width and alligned left.
=> Update sponsors page to be more centered

_sass/common/_extra.scss, images/sponsors/logo_vvvv.png, images/sponsors/ore_system-next_gen_nfts.png, images/sponsors/ore_system-next_gen_nfts_dark.png, index.html, sponsor.html
Diamond open collective sponsor added to Index and sponsors page. 
https://twitter.com/stridedotnet/status/1462111257658597384
ORE System - $1,000 USD since Nov 2021
frontpage:
sponsor page:
=> Ore system - open collective sponsor

_data/features.yml, index.html
C# 9 replaced with C# 10 .NET 6
=> Home Page and Features Page update

.github/workflows/stride-web-staging-azure.yml, .github/workflows/stride-web-wiki.yml
=> Staging next

_data/site.json, _includes/_top-navigation.html, _includes/footer.html, assets/scripts/theme-selector.liquid
- fixes #75 
- fixes #76 
- fixes #77
=> Bugs fixed

.eleventy.js, _data/site.json, download.html, index.html
- Develop once, deploy cross-platform section was updated according the input
- Local download (from web server) was replaced with Direct download from GitHub main repo
=> Final updates

_data/site.json, web.config
=> web.config change reverted

posts/2023-06-07-game-development-in-stride.md
=> feat: Article updated

_includes/carousel_home.html, _includes/carousel_home_caption.html, _includes/hero-section.html, css/styles.scss
#117 
https://github.com/stride3d/stride-website/assets/70596906/3906ceff-8dee-4ff6-9b2b-385857c9dea5
=> add and style hero title & subtitle

_data/site.json
When we update css, we need to change also the version which will help to refresh css as it is a part of the file
`<link rel="stylesheet" href="/css/styles.css?site-version=2.0.0.14">`
=> Update site.json - Version updated to force new css

_data/site.json, package-lock.json, package.json
=> chore: NPM packages bumpted, and tested

Stride.Web.sln
The files were added for easier accessibility in the VS solution.
=> feat: GitHub actions added to Solution Items.

posts/2023-09-14-embracing-open-source-stride-as-an-alternative-to-unity.md
- rendering wording
- title changed to Operating System support
- section How to find answers
- section Closing Thoughts added
=> Final test for the latest updates from the feedbacl

_includes/_head.html
=> Fix for #148

posts/2023-09-14-embracing-open-source-stride-as-an-alternative-to-unity.md
Blog Post:
2023-09-14-embracing-open-source-stride-as-an-alternative-to-unity.md
=> Fix Spelling and Grammar in Unity Migration Blog Post

posts/2023-10-07-community-meeting-october-2023.md
A summary blog of the previous community meeting
=> Adding the community meeting of october 2023

_data/sponsors.json, posts/2023-10-07-community-meeting-october-2023.md
I made lots of markup readability improvements. I didn't touch yet the content itself, just typos.
=> Content improvements

posts/2023-10-07-community-meeting-october-2023.md
Made some contributor display changes and small other feedback on community meeting post
=> Contributor meeting sponsor changes and other feedback

posts/2023-11-10-investigating-spirv-for-the-shader-system.md
Changed the introduction text to a 2 sentence one.
=> update of introduction text

_drafts/2023-11-15-announcing-stride-4-2-in-dotnet-8.md
Adds some text to some of the new features.
Split fixes into its own section
=> Adding some text and split into features and fixes

posts/2023-11-20-announcing-stride-4-2-in-dotnet-8.md
=> feat: Article updated according the release notes

posts/2024-01-05-announcing-stride-4-2-in-dotnet-8.md
Improved section about update pace and funding
added info that Avalonia editor work started.
=> Release blog post 4.2 update

posts/2024-01-05-announcing-stride-4-2-in-dotnet-8.md
Some improvements and typos. Maybe wait if there is more in the next 1-2 days.
=> Release blog post 4.2 improvements and typos

posts/2024-01-05-announcing-stride-4-2-in-dotnet-8.md
What do you think?
Before:
Stride 4.2 includes numerous enhancements and improvements.
- [.NET 8 Integration](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/): Experience the power and efficiency of the latest .NET version in your game development. 
- Full compatibility with .NET 8, taking advantage of [improved runtime performance](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/)
- [C# 12 features](https://devblogs.microsoft.com/dotnet/announcing-csharp-12/): Utilize cutting-edge language features to write more concise and maintainable code, enhancing coding efficiency and reducing boilerplate code
- [Changed Assimp binding to Silk.Net.Assimp](https://github.com/stride3d/stride/pull/1158)
- This change allows us to remove much of the C++/CLR code used …
=> Streamlines feature highlights

posts/2024-03-14-open-worlds-intro-to-foss-game-engines.md
Corrections to the FOSS blog post based on feedback
=> FOSS blog post corrections

.github/workflows/stride-website-staging-azure.yml, _data/site.json, _includes/_top-navigation.html, package-lock.json, package.json
=> feat: Community Resources link added

_data/site.json, _includes/footer.html, package-lock.json, package.json
This pull request includes updates to the site version, package versions, and the addition of a new link in the footer, as well as the addition of license information to several packages.
The site and package versions have been updated, a new link has been added to the footer, and license information has been added to several packages.
- `site.json`: Site version updated from `2.0.0.26` to `2.0.0.27`.
- `footer.html`: Added a new link to "Community Resources".
- `package-lock.json` and `package.json`: Updated versions of `markdown-it-anchor` and `sass`.
- `package-lock.json`: Added license information to several packages, including `sass`.
- `package-lock.json`: Updated versions of several packages, including `pug`, `pug-code-gen`, `pug-error`, and `pug-runtime`.
=> chore: NPM updates

_data/site.json, download.html
This PR add the installation guide link on download page, As said in #80
=> Installation guide link added on download page

.eleventy.js, _includes/_head.html, package-lock.json, package.json, posts/2014-2021/2020-04-20-xenko-has-been-renamed-to-stride.md, posts/2014-2021/2021-10-31-open-collective.md
=> chore: 11ty major version bumped

_data/bronze_sponsors.js, _data/gold_sponsors.js, _data/silver_sponsors.js, _includes/oc_sponsors.njk, css/styles.scss, sponsor.html
Resolves #205 
- Uses eleventy fetch to fetch contributors from opencollective API, cached for 7 days
- Made some style changes
=> feat: Custom contributors widget

_includes/open-collective-sponsors.njk, css/styles.scss, sponsor.html
Style consistency updates.
This pull request enhances the visual presentation of sponsor tiers. Key changes include:
- removed 3rd party dependency
- header styling updated so it closely matches the remaining of the page
- Nunjucks file renamed fro oc.. to open-collective..
=> refactor: Consistency updates in Sponsor section
